defaults:
  - optimizer: adamw
batch_size: 8
mixed_precision: "fp16"
gradient_accumulation_steps: 1
resume_checkpoint: ""
ema:
  beta: 0.996
sequence_length_context: 512
sequence_length_target: 1024
sequence_length_prediction: 1024
commit_loss_weight: 1e-1
entropy_loss_weight: 1.0
entropy_sample_minimization_weight: 10.0
entropy_batch_maximization_weight: 0.1
eval_every_num_steps: 50
dataset:
  path: food101
  type: hf-image
  image_column_name: image
  split: train
  max_res: 256
