defaults:
  - optimizer: adamw
batch_size: 192

resume_checkpoint: ""

accelerator_args:
  mixed_precision: "fp16"
  gradient_accumulation_steps: 1
accelerator_resume_path: ""
save_every_num_steps: 100
accelerator_project_configuration:
  total_limit: 10

gradient_checkpoint: True
ema:
  beta: 0.96
sequence_length_context: 256
sequence_length_target: 768
sequence_length_prediction: 768
commit_loss_weight: 2e-5
entropy_loss_weight: 1e0
entropy_sample_minimization_weight: 1e-5
entropy_batch_maximization_weight: 1e-2

eval_every_num_steps: 100
max_steps: 10001

dataset:
  path: /hdd/imagenet1k/imagenet1k-train-{0000..1023}.tar
  image_column_name: jpg
  max_res: 256
  handler: warn_and_continue

