defaults:
  - optimizer: adamw
batch_size: 16
mixed_precision: "fp16"
gradient_accumulation_steps: 1
resume_checkpoint: ""
ema:
  beta: 0.996
sequence_length_context: 512
sequence_length_target: 1024
sequence_length_prediction: 1024
commit_loss_weight: 1e-5
entropy_loss_weight: 5e0
entropy_sample_minimization_weight: 2e-4
entropy_batch_maximization_weight: 4e-3
eval_every_num_steps: 500
max_steps: 501

dataset:
  path: /hdd/imagenet1k/imagenet1k-train-{0000..1023}.tar
  image_column_name: jpg
  max_res: 256
