defaults:
  - _self_
  - model: base_patch16
  - train: imagenet1k
  - eval: imagenet1k


seed: 42
torch_compile: False
wandb_mode: disabled
num_workers: 4

train:
  dataset:
    crop_to_resolution_multiple_of: ${model.vit.patch_size}


eval:
  batch_size: ${train.batch_size}
  batch_size_validation: ${train.batch_size_validation}
  num_workers: ${num_workers}
  sequence_length: ${train.sequence_length_target}
  optimizer: ${train.optimizer}
  max_iterations: 30
  torch_compile: ${..torch_compile}

  dataset:
    crop_to_resolution_multiple_of: ${model.vit.patch_size}


