defaults:
  - _self_
  - model: base_patch16
  - train: imagenet1k
  - eval: imagenet1k


seed: 42
wandb_mode: online
num_workers: 4

train:
  dataset:
    crop_to_resolution_multiple_of: ${model.vit.patch_size}
  patchnpack_args:
    patch_size: ${model.vit.patch_size}
    batch_size: ${train.batch_size}


eval:
  batch_size: ${train.batch_size}
  num_workers: ${num_workers}
  sequence_length: ${train.sequence_length_target}

  dataset:
    crop_to_resolution_multiple_of: ${model.vit.patch_size}
    max_res: ${train.dataset.max_res}


pretrained_model_path: pretrained-models

model:
  predictor:
    projection_dim: ${model.lfq.codebook_size}
    projection_heads: ${model.lfq.num_codebooks}
    gradient_checkpoint: ${train.gradient_checkpoint}
    input_size: ${model.vit.hidden_size}
  vit:
    gradient_checkpoint: ${train.gradient_checkpoint}
  lfq:
    dim: ${model.vit.hidden_size}
    sample_minimization_weight: ${train.entropy_sample_minimization_weight}
    batch_maximization_weight: ${train.entropy_batch_maximization_weight}

