defaults:
  - _self_
  - model: base_patch32
  - train: default
  - eval: food101

seed: 42
torch_compile: True

train:
  dataset:
    crop_to_resolution_multiple_of: ${model.vit.patch_size}


eval:
  batch_size: ${train.batch_size}
  batch_size_validation: ${train.batch_size_validation}
  num_workers: ${train.num_workers}
  sequence_length: ${train.sequence_length_target}
  optimizer: ${train.optimizer}
  max_iterations: 30
  torch_compile: ${..torch_compile}

  dataset:
    crop_to_resolution_multiple_of: ${model.vit.patch_size}

wandb_mode: disabled
