max_abs_res: 896
patch_size: 14
num_workers: 4
torch_compile: true

train:
  gradient_accumulation_steps: 4
  merge_pretrained_vit: false
  batch_size: 64
  run_eval_every_num_steps: 50000
  save_every_num_steps: 10000
  num_steps: 400000
  warmup_steps: 30000
  log_every_num_steps: 10
  scheduler_scale: 1.25
  start_beta: 0.996
  lr: 7e-4

  mask_args:
    num_prediction_targets: 4

  should_unmerge: true
  teacher_r: 8
  student_r: 4
  merge_mode: drop

dataset_train:
  sequence_length_context: 128
  sequence_length_prediction: 128
  max_abs_res: ${max_abs_res}
  patch_size: ${patch_size}
  num_workers: ${num_workers}
  packer_batch_size: ${..train.batch_size}

  min_side_res: 70
  max_side_res: 252
  resize_mode: crop
  drop_chance: 0.3

  path: /nvme/imagenet1k-256/imagenet1k-train-{0000..1023}.tar
  label_column_name: cls


probe_eval:
  batch_size_encoder: 64
  batch_size_probe: 512
  num_epochs: 50
  val_split: 0.01
  scheduler_scale: 1.25

  r: 8
  merge_mode: drop
  should_unmerge: true

dataset_train_probe:
  sequence_length_context: 1024
  max_abs_res: ${max_abs_res}
  patch_size: ${patch_size}
  num_workers: ${num_workers}

  min_side_res: 448
  max_side_res: 448
  resize_mode: resize
  drop_chance: 0.0

  path: /nvme/imagenet1k/imagenet1k-train-{0000..1023}.tar
  label_column_name: cls
  num_samples: 1281167

dataset_val:
  sequence_length_context: 1024
  max_abs_res: ${max_abs_res}
  patch_size: ${patch_size}
  num_workers: ${num_workers}

  min_side_res: 448
  max_side_res: 448
  resize_mode: resize
  drop_chance: 0.0

  path: /nvme/imagenet1k/imagenet1k-validation-{00..63}.tar
  label_column_name: cls
  num_samples: 50000

vit:
  patch_size: ${patch_size}
  hidden_size: 1024
  depth: 24
  num_attention_heads: 16
  max_height: 64
  max_width: 64
  use_layerscale: false
  use_joint_position_embed: false
  use_bias: false

predictor:
  input_size: 1024
  hidden_size: 384
  depth: 6
  num_attention_heads: 6
  max_height: 64
  max_width: 64
  use_layerscale: false
  use_joint_position_embed: false
  use_bias: false
