dataset:
  path: /hdd/imagenet1k/imagenet1k-validation-{00..63}.tar
  image_column_name: jpg
  num_classes: 1000
  max_res: ${...train.dataset.max_res}
  max_rows: 20000
  handler: warn_and_continue

max_iterations: 80
batch_size: 256
batch_size_validation: 256
optimizer:
  name: AdamW
  args:
    lr: 5e-5
    weight_decay: 5e-2
    betas:
      - 0.9
      - 0.99
